### ISSUE TITLE
Multiple volume levels

### ISSUE THREAD

**Issue by Lasall** [rhaas80/pa_volume#1]
```
./pa_volume
...
client: Firefox 0:  21% 1:  21%
...
```
There are two volume levels displayed behind the applications. When trying to change volume of an application the volume changes unsuspectively, e.g.:
```
./pa_volume Firefox 25
./pa_volume
...
client: Firefox 0:  63% 1:  63%
...
```

**Comment by rhaas80** [comment]
Please try again with the newest version (a7e5f6d a ```git pull``` should do). I made two changes:
1. show only the average volume (before it was one volume per channel)
2. operate on the raw volume that the GUI shows and not the linearized one

**Comment by Lasall** [comment]
Thank you, works like a charm!
