### ISSUE TITLE
pa_volume command not found 

### ISSUE THREAD

**Issue by JerinAbraham2** [rhaas80/pa_volume#12]
I'm pretty new to linux and I'm stuck on this, I pasted this command in the linux command prompt: 

sudo apt-get install pkg-config libpulse-dev pandoc
git clone https://github.com/rhaas80/pa_volume.git
cd pa_volume/
make

it installed fine, but then when I type pa_volume it doesn't work, it says pa_volume command not found.

**Comment by rhaas80** [comment]
The Makefile only compiles the code but does not install it into (say) `/usr/bin/`. To then run it, assuming that `.` is not in your shell's search `$PATH` you will have to do:
```
./pa_volume
```
and similarly to read the man page:
```
man ./pa_volume.1
```

I will try and update the Readme file to mention this, and may also look into adding an `install` target to the Makefile.

For now you would have to manually copy the executable into say `/usr/local/bin/` (or maybe better `$HOME/bin` if that is in your `$PATH`) and the manpage file in to `/usr/local/share/man/man1/` or equivalent in `$HOME/share/man/man1` if that is in your `$MANPATH`).
