### ISSUE TITLE
Document also how it can be installed in alpine

### ISSUE THREAD

**Issue by janvda** [rhaas80/pa_volume#14]
The readme documents how it can be installed in debian/ubuntu.

It would also be interesting to document how it can be installed in alpine linux.

**Comment by janvda** [comment]
FYI I managed to install it in an alpine docker container (docker hub version `alpine:3.17.1`)
with following docker commands:

```
# installing pa_volume (https://github.com/rhaas80/pa_volume)
RUN set -ex && apk --no-cache add  build-base libpulse pulseaudio-dev make git
RUN cd /tmp && \
    git clone https://github.com/rhaas80/pa_volume.git && \
    cd pa_volume && \
    PKG_CONFIG_PATH=/usr/lib  make && \
    cp  pa_volume /usr/local/bin 
```

**Comment by rhaas80** [comment]
Sure. Done.
