### ISSUE TITLE
after installation on raspberry pi bullseye command not found

### ISSUE THREAD

**Issue by lxne** [rhaas80/pa_volume#15]
Hi, I am trying to use this on a raspberry pi with bullseye, but after the installation the command is not found. Am I missing something?

```
cd pa_volume/
make
cc -O2 -std=c99 -Wall -o pa_volume pa_volume.c -lpulse
pandoc --standalone --to man pa_volume.1.md -o pa_volume.1
echo "All done"
All done
~/pa_volume $ pa_volume
-bash: pa_volume: command not found.
```

**Comment by rhaas80** [comment]
Most likely your `$PATH` variable does not include the directory `pa_volume` is in. Looking at your commands, most likely that would be `.`. So you can try `./pa_volume` and that should work since it gives the path to it.

**Comment by lxne** [comment]
Thank you for your reply.

With `./pa_volume` the response is `-bash: ./pa_volume: Is a folder`.
But `./pa_volume/pa_volume` works.
