### ISSUE TITLE
exception when trying to set the volume for an application

### ISSUE THREAD

**Issue by gbuntu127** [rhaas80/pa_volume#2]
Hi, I happen to find your answer on [stackoverflow](https://unix.stackexchange.com/questions/131827/somehow-managed-to-mute-mplayer-and-cant-figure-out-how-to-restore-sound) , thanks for the great tool. 

I am trying to set the volume for an application. i.e., gmplayer on linux mint Sarah 18 (=ubuntu 16.04). I was able to build your code and it listed the applications and their volumes as expected. e.g,:

```
$ ./pa_volume
client: Firefox 100%
client: ALSA plug-in [java]   0%
client: LibreOffice 5.1   0%
client: Audacious  23%
client: Opera   0%
client: speech-dispatcher   0%
client: gmplayer   0%
```
However, when I tried to set the volume for gmplayer:
```
$ ./pa_volume gmplayer 100
Assertion 'o' failed at pulse/operation.c:67, function pa_operation_unref(). Aborting.
Aborted
```

Do you know what the problem it might be? Thanks for helping!

**Comment by rhaas80** [comment]
Hello,

I am not sure what exactly is causing this. On the other hand there was
no error checking whatsover in pa_volume so far.

I have now added some and also (based on a hunch) extended the way that
pa_volume tries to handle clients whose stored record is incomplete
(which let's me avoid some errors on my own laptop).

Please give it a try (git pull ; make) and let me know if this fixes
your issue.

Also it may help to (if possible) use pavucontrol to set gmplayer's
volume once to enforce a stored record. If that helps, please also let
me know and I will try and extend the workaround once more.

Yours,
Roland

> Hi, I happen to find your answer on [stackoverflow](https://unix.stackexchange.com/questions/131827/somehow-managed-to-mute-mplayer-and-cant-figure-out-how-to-restore-sound) , thanks for the great tool. 
> 
> I am trying to set the volume for an application. i.e., gmplayer on linux mint Sarah 18 (=ubuntu 16.04). I was able to build your code and it listed the applications and their volumes as expected. e.g,:
> 
> ```
> $ ./pa_volume
> client: Firefox 100%
> client: ALSA plug-in [java]   0%
> client: LibreOffice 5.1   0%
> client: Audacious  23%
> client: Opera   0%
> client: speech-dispatcher   0%
> client: gmplayer   0%
> ```
> However, when I tried to set the volume for gmplayer:
> ```
> $ ./pa_volume gmplayer 100
> Assertion 'o' failed at pulse/operation.c:67, function pa_operation_unref(). Aborting.
> Aborted
> ```
> 
> Do you know what the problem it might be? Thanks for helping!
> 
> 



-- 
My email is as private as my paper mail. I therefore support encrypting
and signing email messages. Get my PGP key from http://keys.gnupg.net.

**Comment by gbuntu127** [comment]
The update works great, now my stored record has been updated correctly. 
Thanks for your help!
